server:
  port: 8093

spring:
  application:
    name: xuyou-config
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        server-addr: localhost:8848
        namespace: public
        file-extension: yml
        group: DEFAULT_GROUP
        import-check:
          enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.alibaba.nacos: info
    org.springframework.cloud: info
