server:
  port: 8091

spring:
  application:
    name: xuyou-gateway
  main:
    web-application-type: reactive

  config:
    import:
      - optional:application-gateway.yml
      - optional:application-actuator.yml
      - optional:application-redis.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

logging:
  level:
    org.springframework.cloud.gateway: info
    org.springframework.http.server.reactive: info
    org.springframework.web.reactive: info
    reactor.netty: info
